### ISSUE TITLE
Credential dont appear on the list to be created

### ISSUE THREAD

**Issue by felipe-negri** [Airthee/n8n-nodes-qbittorrent#1]
![image](https://github.com/user-attachments/assets/2d236366-168f-4679-b55e-36d661571149)

when i install the n8n-nodes-qbittorrent-hsn version i can create crendential

**Comment by felipe-negri** [comment]
i make the fix and test in docker n8n and works #2

**Comment by Airthee** [comment]
Tested, merged and published, thanks !
